version: '3.8'
services:
  spring-app:
    build: .
    ports:
      - "8080:8080"
        # user: "0:0" # Dies erzwingt Root-Rechte für den Schreibzugriff auf /data
      # 'nobody' ist ein Standard-User mit minimalen Rechten
    user: "0:0"
    volumes:
      - h2_data:/data
    restart: always
    environment:
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_H2_CONSOLE_SETTINGS_WEB_ADMIN_PASSWORD=${SPRING_H2_CONSOLE_SETTINGS_WEB_ADMIN_PASSWORD}
volumes:
  h2_data: