version: '3.8'
services:
  spring-app:
    build: .
    ports:
      - "8080:8080"
    user: "0:0" # Dies erzwingt Root-Rechte für den Schreibzugriff auf /data
    volumes:
      - h2_data:/data
    restart: always

volumes:
  h2_data: