spring.application.name=pub-quizzz
server.forward-headers-strategy=framework
spring.h2.console.enabled=false
spring.h2.console.settings.web-allow-others=true
spring.datasource.url=jdbc:h2:file:/data/pubquizzz;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# File upload
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
app.upload.dir=/data/uploads
app.backup.restore-dir=/data/pending-restore
spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false
